//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kurs3
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип атрибутов.
    /// </summary>
    // *** Start programmer edit section *** (ТипАтр CustomAttributes)

    // *** End programmer edit section *** (ТипАтр CustomAttributes)
    public enum ТипАтр
    {
        
        // *** Start programmer edit section *** (ТипАтр.string CustomAttributes)

        // *** End programmer edit section *** (ТипАтр.string CustomAttributes)
        @string,
        
        // *** Start programmer edit section *** (ТипАтр.int CustomAttributes)

        // *** End programmer edit section *** (ТипАтр.int CustomAttributes)
        @int,
        
        // *** Start programmer edit section *** (ТипАтр.float CustomAttributes)

        // *** End programmer edit section *** (ТипАтр.float CustomAttributes)
        @float,
        
        // *** Start programmer edit section *** (ТипАтр.DateTime CustomAttributes)

        // *** End programmer edit section *** (ТипАтр.DateTime CustomAttributes)
        DateTime,
        
        // *** Start programmer edit section *** (ТипАтр.bool CustomAttributes)

        // *** End programmer edit section *** (ТипАтр.bool CustomAttributes)
        @bool,
        
        // *** Start programmer edit section *** (ТипАтр.double CustomAttributes)

        // *** End programmer edit section *** (ТипАтр.double CustomAttributes)
        @double,
    }
}
